sudo: required
language: go

go:
  - 1.6.x
  - 1.7.x
  - tip

cache:
  directories:
    - vendor
    - ${HOME}/.glide

before_install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - make dep_install

script:
  - make vet
  - make lint
  - make test
  - make build
